---
monitoring_dir: /opt/monitoring
grafana_admin_user: admin
grafana_port: 3000
prometheus_retention_time: 15d
prometheus_retention_size: 8GB
loki_retention: 336h
node_exporter_port: 9100
monitoring_instance_name: monitoring-vps
