---
- name: Ensure Docker is Running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Run Node Exporter container
  community.docker.docker_container:
    name: node_exporter
    image: quay.io/prometheus/node-exporter:latest
    state: started
    restart_policy: unless-stopped
    network_mode: host
    pid_mode: host  
    volumes:
      - /:/host:ro,rslave
    command: --path.rootfs=/host